### ISSUE TITLE
The months and weekdays are shown in English regardless of current configured language

### ISSUE THREAD

**Issue by dfilatov** [gravity-ui/date-components#137]
<img width="352" alt="image" src="https://github.com/user-attachments/assets/ab810ba3-56b4-4c30-b10c-8092375ac2c2">

Expected behaviour: months and weekdays are shown in language according to configured via `configureUiKit`.

**Comment by korvin89** [comment]
@dfilatov Hi!

It is a little bit tricky to change locale for `DatePicker` because of [date-utils](https://github.com/gravity-ui/date-utils) usage. [Here](https://stackblitz.com/edit/vitejs-vite-fdz8lg?file=src/main.tsx:L21) you can find an example of locale changing.

You can reopen this issue if you still have questions.

**Comment by dfilatov** [comment]
@korvin89 It works, thank you!
